import * as XLSX from 'xlsx';import type{Ativo}from'../tipos/Ativo';import{COLUNAS_PLANILHA}from'../tipos/Ativo';import{numeroMoeda}from'../utilitarios/formatadores';import{normalizarIP,atualizarObsolescencia}from'../utilitarios/regrasNegocio';import type{ErroValidacao}from'../tipos/Sistema';
const pegar=(r:Record<string,unknown>,...n:string[])=>{for(const x of n)if(r[x]!==undefined&&r[x]!==null)return r[x];return''};const str=(v:unknown)=>v==null?'':String(v).trim();
export function linhaParaAtivo(r:Record<string,unknown>,i:number){const ip=normalizarIP(str(pegar(r,'IP Address','IP')),i+2);const now=new Date().toISOString();const a:Ativo={id:str(pegar(r,'ID','Id','id','__PowerAppsId__'))||crypto.randomUUID(),country:str(pegar(r,'Country','País','Pais')),needsReview:str(pegar(r,'NeedsReview','Needs Review'))||'No',location:str(pegar(r,'Location','Localização','Localizacao')),costRegion:str(pegar(r,'Cost Region')),serialNumber:str(pegar(r,'Serial Number','Serial')),hostname:str(pegar(r,'Hostname','Host Name')),lastHostname:str(pegar(r,'Last Hostname')),currentStatus:str(pegar(r,'Current Status','Status'))||'Desconhecido',caf:str(pegar(r,'CAF')),answeringICMP:str(pegar(r,'AnsweringICMP')),ipAddress:ip.valor,macAddress:str(pegar(r,'MAC Address','MAC')),source:str(pegar(r,'Coluna1','Source','Origem'))||'Planilha',snmpLocated:str(pegar(r,'SNMPLocated')),isNew:str(pegar(r,'IsNew')),wasReplaced:str(pegar(r,'WasReplaced')),model:str(pegar(r,'Model','Modelo')),approverGroupBusiness:str(pegar(r,'Approver Group Business')),subLocation:str(pegar(r,'Sub Location (Galpão)','Sub Location','Sublocalização')),vendor:str(pegar(r,'Vendor','Fabricante')),vendorSupported:str(pegar(r,'Vendor Supported')),endOfContract:str(pegar(r,'End of Contract')),siteCode:str(pegar(r,'Site Code')),simpleDeviceCategory:str(pegar(r,'Simple Device Category','Device Category')),deviceGroup:str(pegar(r,'Device Group')),obsoleteYear:str(pegar(r,'Obsolete Year')),capex:str(pegar(r,'Capex','CAPEX')),opex:numeroMoeda(pegar(r,'Opex','OPEX')),isObsolete:str(pegar(r,'Is Obsolete?','Is Obsolete'))||'No',plannedReplacementYear:str(pegar(r,'Planned Replacement Year')),speedUpPlan:str(pegar(r,'Speed Up Plan')),type:str(pegar(r,'Type','Tipo')),unitValue:numeroMoeda(pegar(r,'Unit Value')),serviceUnitCost:numeroMoeda(pegar(r,'Service Unit Cost')),replacementCost:numeroMoeda(pegar(r,'Replacement Cost')),technicalReserve:numeroMoeda(pegar(r,'Technical Reserve')),powerAppsId:str(pegar(r,'__PowerAppsId__')),assetId:str(pegar(r,'Snipe Asset ID','asset_id')),assetTag:str(pegar(r,'Asset Tag','asset_tag')),snmpStatus:str(pegar(r,'SNMP Status')),interfaceInfo:str(pegar(r,'Interface')),dupHost:false,deletedAt:'',deletedBy:'',origem:'Planilha',updatedAt:now,createdAt:now,createdBy:'Importação',deliveryStatus:str(pegar(r,'Delivery Status')),installStatus:str(pegar(r,'Install Status')),invoice:str(pegar(r,'Invoice','Nota Fiscal')),receivedAt:str(pegar(r,'Received At','Data de Recebimento')),supportLevel:str(pegar(r,'Support Level')),supportProvider:str(pegar(r,'Support Provider'))};if(ip.aviso)a.needsReview='Yes';return{ativo:atualizarObsolescencia(a),avisos:ip.aviso?[ip.aviso]:[] as ErroValidacao[]}}
export async function importarPlanilha(file:File){const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(ws,{defval:''});const ativos:Ativo[]=[];const avisos:ErroValidacao[]=[];rows.filter(r=>Object.values(r).some(v=>str(v))).forEach((r,i)=>{const x=linhaParaAtivo(r,i);ativos.push(x.ativo);avisos.push(...x.avisos)});return{ativos,avisos}}
function linha(a:Ativo){return{'Country':a.country,'NeedsReview':a.needsReview,'Location':a.location,'Cost Region':a.costRegion,'Serial Number':a.serialNumber,'Hostname':a.hostname,'Last Hostname':a.lastHostname,'Current Status':a.currentStatus,'CAF':a.caf,'AnsweringICMP':a.answeringICMP,'IP Address':a.ipAddress,'Coluna1':a.source,'SNMPLocated':a.snmpLocated,'IsNew':a.isNew,'WasReplaced':a.wasReplaced,'Model':a.model,'Approver Group Business':a.approverGroupBusiness,'Sub Location (Galpão)':a.subLocation,'Vendor':a.vendor,'Vendor Supported':a.vendorSupported,'End of Contract':a.endOfContract,'Site Code':a.siteCode,'Simple Device Category':a.simpleDeviceCategory,'Device Group':a.deviceGroup,'Obsolete Year':a.obsoleteYear,'Capex':a.capex,'Is Obsolete?':a.isObsolete,'Planned Replacement Year':a.plannedReplacementYear,'Speed Up Plan':a.speedUpPlan,'Type':a.type,'Unit Value':a.unitValue,'Service Unit Cost':a.serviceUnitCost,'Replacement Cost':a.replacementCost,'Technical Reserve':a.technicalReserve}}
export function exportarExcel(a:Ativo[]){const ws=XLSX.utils.json_to_sheet(a.map(linha),{header:[...COLUNAS_PLANILHA]});const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Inventário');XLSX.writeFile(wb,`SniperIT_IMPORT_${new Date().toISOString().slice(0,10)}.xlsx`)}
export function exportarCsv(a:Ativo[]){const ws=XLSX.utils.json_to_sheet(a.map(linha));const blob=new Blob(['\ufeff'+XLSX.utils.sheet_to_csv(ws,{FS:';'})]);const u=URL.createObjectURL(blob);const x=document.createElement('a');x.href=u;x.download='SniperIT_IMPORT.csv';x.click();URL.revokeObjectURL(u)}
export function baixarModelo(){const ws=XLSX.utils.aoa_to_sheet([[...COLUNAS_PLANILHA]]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Inventário');XLSX.writeFile(wb,'modelo-SniperIT_IMPORT.xlsx')}

/**
 * Gera uma versão imprimível dos ativos selecionados.
 * No navegador, escolha "Salvar como PDF" na janela de impressão.
 * Mantemos assim para não adicionar uma biblioteca pesada apenas para PDF.
 */
export function exportarPdf(a:Ativo[]){
  if(!a.length)return;
  const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]||c));
  const linhas=a.map(x=>`<tr><td>${esc(x.hostname)}</td><td>${esc(x.serialNumber)}</td><td>${esc(x.ipAddress)}</td><td>${esc(x.vendor)}</td><td>${esc(x.model)}</td><td>${esc(x.location)}</td><td>${esc(x.currentStatus)}</td><td>${esc(x.plannedReplacementYear)}</td><td>${esc(x.isObsolete)}</td></tr>`).join('');
  const w=window.open('','_blank','width=1200,height=800');
  if(!w){alert('O navegador bloqueou a janela de impressão. Permita pop-ups para gerar o PDF.');return;}
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Inventário CMDB</title><style>body{font-family:Arial,sans-serif;padding:24px;color:#172033}h1{margin:0 0 5px}p{color:#667085;margin:0 0 20px}table{width:100%;border-collapse:collapse;font-size:10px}th,td{border:1px solid #d0d5dd;padding:6px;text-align:left}th{background:#f2f4f7}@page{size:landscape;margin:10mm}</style></head><body><h1>Sniper IT CMDB</h1><p>${a.length} ativo(s) selecionado(s) • ${new Date().toLocaleString('pt-BR')}</p><table><thead><tr><th>Hostname</th><th>Serial</th><th>IP</th><th>Fabricante</th><th>Modelo</th><th>Location</th><th>Status</th><th>Planned Year</th><th>Obsoleto</th></tr></thead><tbody>${linhas}</tbody></table><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`);
  w.document.close();
}
